#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-jupyter_server_mathjax
Version  : 0.2.3
Release  : 3
URL      : https://files.pythonhosted.org/packages/f1/6f/aaa531dfcfd5b2179184beccf246401db7fe6d860a77993daf471fc14594/jupyter_server_mathjax-0.2.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/f1/6f/aaa531dfcfd5b2179184beccf246401db7fe6d860a77993daf471fc14594/jupyter_server_mathjax-0.2.3.tar.gz
Summary  : MathJax resources as a Jupyter Server Extension.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: pypi-jupyter_server_mathjax-license = %{version}-%{release}
Requires: pypi-jupyter_server_mathjax-python = %{version}-%{release}
Requires: pypi-jupyter_server_mathjax-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: jupyter_server_mathjax
Provides: jupyter_server_mathjax-python
Provides: jupyter_server_mathjax-python3
BuildRequires : pypi(jupyter_packaging)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
# MathJax resources endpoints for Jupyter Server
![Testing](https://github.com/jupyter-server/jupyter_server_mathjax/workflows/Testing/badge.svg)

%package license
Summary: license components for the pypi-jupyter_server_mathjax package.
Group: Default

%description license
license components for the pypi-jupyter_server_mathjax package.


%package python
Summary: python components for the pypi-jupyter_server_mathjax package.
Group: Default
Requires: pypi-jupyter_server_mathjax-python3 = %{version}-%{release}

%description python
python components for the pypi-jupyter_server_mathjax package.


%package python3
Summary: python3 components for the pypi-jupyter_server_mathjax package.
Group: Default
Requires: python3-core
Provides: pypi(jupyter_server_mathjax)
Requires: pypi(jupyter_server)

%description python3
python3 components for the pypi-jupyter_server_mathjax package.


%prep
%setup -q -n jupyter_server_mathjax-0.2.3
cd %{_builddir}/jupyter_server_mathjax-0.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641451499
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jupyter_server_mathjax
cp %{_builddir}/jupyter_server_mathjax-0.2.3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupyter_server_mathjax/4a3ccb8c03802d2981db7856c534491a854e6741
cp %{_builddir}/jupyter_server_mathjax-0.2.3/jupyter_server_mathjax/static/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jupyter_server_mathjax/2b8b815229aa8a61e483fb4ba0588b8b6c491890
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_server_config.d/jupyter_server_mathjax.json

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jupyter_server_mathjax/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-jupyter_server_mathjax/4a3ccb8c03802d2981db7856c534491a854e6741

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
